# Dependencies
markdown:         kramdown
# pygments:         true

# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:        /:year/:month/:day/:title/


# Setup
title:            "Oreki47"
name:             "Cao's Weeblog"
tagline:          "-------------"
description:      "This guy is a weeb -- Most of the stuff I write is for myself. I try to archive most of the tech/general things I encounter in my life so I could skip the searching part by just reading my own post and figure it out later again."
url:              "https://oreki47.github.io"
paginate:         5

# About
author:           
name:             "Zhiyuan Cao"
url:                          

paginate:         5

# Custom vars
version:          2.0.0

github:           
  repo:           https://github.com/Oreki47/Oreki47.github.io


# Gems
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate