# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:year/:month/:day/:title/


# Setup
title:            "Cao's Weeblog"
name:             "Cao's Weeblog"
tagline:          "A blog about what?"
description:      "This guy is a weeb"
url:              "https://oreki47.github.io"
paginate:         5

# About
author:           
name:             "Zhiyuan Cao"
url:                          

paginate:         5

# Custom vars
version:          2.0.0

github:           
  repo:           https://github.com/Oreki47/Oreki47.github.io
