# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Blog
tagline:          
description:      'This is Zhiyuan Cao'
url:              

author:
  name:           
  url:            

paginate:         5

# Custom vars
version:          2.0.0

github:           https://github.com/Oreki47
  repo:           https://github.com/Oreki47/Oreki47.github.io
